export enum AssetKey {
    PoolBackground = "poolBackground",
    SlideForeground = "slideForeground",
    SlideTowerBase = "slideTowerBase",
    SlideTowerTop = "slideTowerTop",
    UnderWaterBackground = "underWaterBackground",
    UnderWaterMidground = "underWaterMidground",
    UnderWaterForeground = "underWaterForeground",
    UnderWaterSand = "underWaterSand",
    UnderWaterGodRay0 = "underWaterGodRay0",
    UnderWaterGodRay1 = "underWaterGodRay1",
    Rubik = "rubik",

    CGloom = "cgloom",
    CSlime = "cslime",
    Ekaling = "ekaling",
    HBlackMage = "hblackmage",
    HDarknell = "hdarknell",
    HLotus = "hlotus",
    HWill = "hwill",
    HLucid = "hlucid",
    HSeren = "hseren",
    NDarknell = "ndarknell",
    NGloom = "ngloom",
    NKalos = "nkalos",
    NLucid = "nlucid",
    NSlime = "nslime",
    NVHilla = "nvhilla",
    NWill = "nwill",
    Urchin = "urchin"
}
